language: python
python:
  - "2.7"

# command to install dependencies
virtualenv:
  system_site_packages: true

sudo: false

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran

install:
 - pip install -r requirements.txt

# Run tests
# Only compare after 15 lines of netcdfs, because old versions don't include 'string' specifier
script:
 - ./tropict/examples/process_ncdf.sh
 - ncdump tropict/bio-2b.nc4 | tail -n +`ncdump tropict/bio-2b.nc4 | grep -n "data:" | cut -f1 -d:` > tropict/bio-2b.nc4.txt
 - head -n 40 tropict/bio-2b.nc4.txt
 - ncdump tropict/examples/subjects/bio-2b.nc4 | tail -n +`ncdump tropict/examples/subjects/bio-2b.nc4 | grep -n "data:" | cut -f1 -d:` > tropict/examples/subjects/bio-2b.nc4.txt
 - head -n 40 tropict/examples/subjects/bio-2b.nc4.txt
 - cmp tropict/bio-2b.nc4.txt tropict/examples/subjects/bio-2b.nc4.txt
 - ./tropict/examples/process_image.sh
 - cmp tropict/arabica-futureb.png tropict/examples/subjects/arabica-futureb.png
 - ./tropict/examples/process_shapefile.sh
 - cmp tropict/examples/countries.shp tropict/examples/countries2.shp