language: python
python:
  - "2.7"

# command to install dependencies
virtualenv:
  system_site_packages: true

install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libhdf5-serial-dev
 - pip install -r requirements.txt

# Run tests
script:
 - ./tropict/examples/process_ncdf.sh
 - cmp bio-2b.nc4 tropict/examples/subjects/bio-2b.nc4
 - ./tropict/examples/process_image.sh
 - cmp arabica-futureb.png tropict/examples/subjects/arabica-futureb.png
