language: python
python:
  - "2.7"

# command to install dependencies
virtualenv:
  system_site_packages: true

sudo: false

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran

install:
 - pip install -r requirements.txt

# Run tests
script:
 - ./tropict/examples/process_ncdf.sh
 - ls
 - ls tropict
 - ls tropict/examples
 - ls tropict/examples/subjects
 - cmp tropict/examples/bio-2b.nc4 tropict/examples/subjects/bio-2b.nc4
 - ./tropict/examples/process_image.sh
 - cmp tropict/examples/arabica-futureb.png tropict/examples/subjects/arabica-futureb.png
